on:
  push:
    branches:
      - main
      - ci/**
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: devcontainers/ci@v0.3
        with:
          runCmd: npm ci

      - uses: devcontainers/ci@v0.3
        with:
          runCmd: npm test
