name: test

on:
  push:
    branches:
    - main
    - ci/**
  pull_request:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Start devcontainer
      uses: jehon/actions-devcontainer@main
      with:
        action: start

    - name: npm ci
      uses: jehon/actions-devcontainer@main
      with:
        run: npm ci
    
    - name: npm test
      uses: jehon/actions-devcontainer@main
      with:
        run: npm test
