on:
  push:
    branches:
      - main
      - ci/**
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - uses: devcontainers/ci@v0.3
        with:
          runCmd: npm ci

      - uses: devcontainers/ci@v0.3
        with:
          runCmd: npm test
